databases:
  - name: brandea-crm-db
    databaseName: brandea_crm
    user: brandea_user
    plan: free

services:
  - type: web
    name: brandea-api
    runtime: node
    repo: https://github.com/Brandea-ai/brandea-crm
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: brandea-crm-db
          property: connectionString