services:
  - type: web
    name: brandea-api
    runtime: node
    repo: https://github.com/Brandea-ai/brandea-crm
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/brandea_crm.sqlite
    disk:
      name: sqlite-storage
      mountPath: /var/data
      sizeGB: 1